# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82179308ce9e46a5d0b13e4a63065ac00c0aa06cb0c0fb90cdaaeaed3dac621f9e6e1118d9d2f1291e5a50874b7f988385da67f4d31e602ffb7f4c38c2583e1c

test:
  secret_key_base: 2ccaceed64d1084ed2fba84af3a150bae1c0016e44b2a51950469afffc2a02ceccd9931212ab3ae91db2a2d87221067306a4aa7997bef61f2864c45e58629c6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
